name: My First Workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: Welcome Message
              run: echo "Welcome Message $(date)"
            
            - name: List files
              run: ls
            # This will have error, cos file in not found
            - name: Read file
              run: cat README.md