name: Pass Data via Artifact
on: push
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - run: |
                ls
                echo "Start build at $(date)" >> runner.log
                echo "Upload Build artifacts" >> runner.log
            - uses: actions/upload-artifact@v4
              with:
                name: runner
                path: runner.log
            - run: echo "varMyBuildVersion=1.0" >> $GITHUB_ENV
            - run: echo "${{ env.varMyBuildVersion }}"
    deploy:
        needs: [build]
        runs-on: ubuntu-latest
        steps:
            - uses: actions/download-artifact@v4
              with:
                name: runner
            - run: echo "My build version is ${{ env.varMyBuildVersion }}" >> runner.log
            - run: cat runner.log
