name: Pass Data via Artifact
on: push
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - run: ls
            - run: echo "Start build at $(date)" >> runner.log
            - run: echo "Upload Build artifacts" >> runner.log
            - uses: actions/upload-artifact@v4
              with:
                name: runner
                path: runner.log
    deploy:
        needs: [build]
        runs-on: ubuntu-latest
        steps:
            - uses: actions/download-artifact@v4
              with:
                name: runner
            - run: cat runner.log
