name: Pass Data Via Env
on: push
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - run: echo "varVersion=1" >> $GITHUB_ENV
    deploy:
        needs: [build]
        runs-on: ubuntu-latest
        steps:
            - run: echo "${{ env.varVersion }}"
            - name: Set Output
              id: step1
              run: echo "::set-output name=my_output::my_value"
            - name: Use Output
              run: echo "${{ steps.step1.outputs.my_output }}"